apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "4"
  generation: 1
  labels:
    run: kubedemo
  name: kubedemo
  selfLink: /apis/extensions/v1beta1/namespaces//deployments/kubedemo
spec:
  replicas: 3
  selector:
    matchLabels:
      run: kubedemo
  strategy:
    rollingUpdate:
      maxSurge: 10
#      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: kubedemo
    spec:
      containers:
      - command:
        - node
        - app/server.js
        image: gcr.io/kubeconcph/democontainer:v10
        imagePullPolicy: IfNotPresent
        name: democontainer
        ports:
        - containerPort: 80
          protocol: TCP
        readinessProbe:
          failureThreshold: 10
          httpGet:
            path: /
            port: 80
            scheme: HTTP
          initialDelaySeconds: 3
          periodSeconds: 1
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 20m
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
